services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data: